###
GET http://localhost:8888
Accept: application/json

###
GET http://localhost:8888/user-service.properties
Accept: application/json

###
GET http://localhost:8888/user-service/default
Accept: application/json

###
GET http://localhost:8888/user-service/dev
Accept: application/json

###
GET http://localhost:8888/user-service/test
Accept: application/json

#################################################################### microservice-a
### Get config file of microservice-a.
GET http://localhost:8888/microservice-a.yaml

#################################################################### microservice-a
### Get config file of microservice-a.
GET http://localhost:8888/microservice-b.yaml
